language: python
cache: pip
services:
  - docker
jobs:
  include:
    - stage: Python tests
      python: 3.6
      install:
        - pip install -r dev_requirements.txt
      script: 
        - pytest --cov=swaggertosdk
      after_success:
        - coveralls
    - stage: Docker testing
      script:
        - docker build -t testing .
