language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: 
  - nosetests --with-coverage
after_success:
  - coveralls