apiVersion: v1
kind: Service
metadata:
  name: restserverts-service
  namespace: swaggertosdk
spec:
  selector:
    app: restserverts
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
