apiVersion: v1
kind: Service
metadata:
  name: restservergo-service
  namespace: swaggertosdk
spec:
  selector:
    app: restservergo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer
